### ISSUE TITLE
Error in Twitter based URL scraping

### ISSUE THREAD

**Issue by jashmehta3300** [SimPPL/twitter-scraping#4]
URLs like “twitter.com/TomTiffanyWI/status/1265248726215528449" do not yield any results on Twitter but they do exist on Twitter (e.g. https://twitter.com/search?q=twitter.com%2FTomTiffanyWI%2Fstatus%2F1265248726215528449&src=typed_query)

Swapneel's suggestion: this means we need to retrieve the tweet by ID and NOT search for a Twitter URL on Twitter itself. But what about URLs from other platforms that exhibit the same ‘non-searchable’ behavior? We needs more triage to check if this is the case only for Twitter URLs or also for other URLs (e.g. Facebook URLs) on Twitter

**Comment by deep1401** [comment]
This might be happening because the `quoted tweets` aren't treated as urls but have a separate place in the tweet object. Will have a look!
